"use client"
import { useTest } from "@/hooks/useTest";
import { useEffect, useState } from "react";
import TestsList from "./TestList";
import TestListLoading from "./TestListLoading";


export default function PageA() {

    // const tests = [
    //     "1,25 Vitamin D",
    //     "1p36 Deletion Syndrome – karyotype + CGH",
    //     "2-Butanone GC",
    //     "2-Furoic Acid",
    //     "5 HIAA",
    //     "5’ Nucleotidase",
    //     "6-Thioguanine Nucleotides",
    //     "7 STI Profile by PCR (7 tests from 1 Sample)",
    //     "7 STI Profile by PCR (7 tests from 1 Sample) (Self-collect)",
    //     "11 Deoxycorticosterone",
    //     "11 Deoxycortisol",
    //     "16S rRNA Bacterial Gene",
    //     "17 Hydroxyprogesterone",
    //     "18S rRNA Fungal Gene",
    //     "21 Hydroxylase Ab’s",
    //     "21-Hydroxylase Deficiency (Congenital Adrenal Hyperplasia)",
    //     "22q11 & 10p14 deletion (Di George Syndrome) – BOBs only",
    //     "22q11 & 10p14 deletion (Di George Syndrome) – BOBs (5 days) + karyotype (15 days)",
    //     "Acetone – Blood",
    //     "Acetone – Urine",
    //     "Acetylcholine Receptor Autoantibodies",
    //     "Achromatopsia NGS Panel",
    //     "Acid Phosphatase – Total",
    //     "ACTH (Adrenocorticotropic Hormone)",
    //     "Activated Protein C Resistance",
    //     "Acute Viral Hepatitis Screen",
    //     "ADAMTS-13 Antibody",
    //     "Adenomatous Polyposis NGS Panel",
    //     "Adiponectin",
    //     "Adrenal Cortex Antibodies",
    //     "Afibrinogenemia, congenital",
    //     "Aicardi-Goutières Syndrome NGS Panel",
    //     "Alagille Syndrome NGS Panel",
    //     "Albumin",
    //     "Alcohol (Medical)",
    //     "Alcohol (Urine)",
    //     "Alcohol Profile",
    //     "Aldolase",
    //     "Aldosterone",
    //     "Aldosterone (Urine)",
    //     "ALEX® Allergy Test (Venous / Self-collect)",
    //     "Alkaline Phosphatase",
    //     "Alkaline Phosphatase Isoenzymes",
    //     "Allergic Rhinitis/Asthma Profile",
    //     "Allergy – Individual Allergens",
    //     "Allergy – 10 x Single Individual Allergens",
    //     "Allergy Profile 1 (Food & Inhalants)",
    //     "Allergy Profile 2 (UK Aero Allergen)",
    //     "Allergy Profile 3 (Food)",
    //     "Allergy Profile 4 (Nuts & Seeds)",
    //     "Allergy Profile 5 (Children’s Panel)",
    //     "Allergy Profile 7 (Finfish)",
    //     "Allergy Profile 6 (Shellfish)",
    //     "Allergy Profile 8 (Cereal – singles)",
    //     "Allergy Profile 9 (Antibiotics)",
    //     "Allergy Profile 10 (Insects)",
    //     "Allergy Profile 11 (Combined Shellfish/Finfish)",
    //     "Allergy Profile 12 (Milk & Milk Proteins)",
    //     "Allergy Profile 13 (Stone fruit/Rosaceae family)",
    //     "Gaucher Disease full gene sequencing",
    //     "H. pylori Antigen – Stool (Self-collect)",
    //     "Hazelnut Components",
    //     "Hepatitis A, B & C Profile",
    //     "B cell clonality assay (IgH and IgK)",
    //     "Babesia PCR",
    //     "Bancroftia/Oncerciasis/Filarial Antibodies",
    //     "Bardet-Biedl Syndrome NGS Panel",
    //     "Batten Disease (Neuronal Ceroid Lipofuscinosis) NGS Panel",
    //     "BCR-ABL Diagnostic Assay",
    //     "BCR/ABL Quantitative – fusion gene sizes p190 + p210",
    //     "Becker/Duchenne Muscular Dystrophy – deletions/duplications",
    //     "Beckwith-Wiedemann Syndrome – methylation studies on 11p15 imprinting domains KvDMR + H19",
    //     "Behcet’s Disease – HLA Tissue Typing B*51",
    //     "Bence-Jones Protein",
    //     "Benzene",
    //     "Bernard-Soulier Syndrome",
    //     "Beta 2 Microglobulin (Serum)",
    //     "Beta 2 Microglobulin (Urine)",
    //     "Beta Carotene",
    //     "Beta D Glucan",
    //     "Beta Thalassaemia – beta-globin gene sequencing",
    //     "Beta-Glucuronidase (Sly Disease)",
    //     "Bicarbonate",
    //     "Bile Acids – Serum",
    //     "Bilharzia (Schistosome) Antibody Screen",
    //     "Bilharzia (Urine)",
    //     "Bilirubin (Direct)",
    //     "Bilirubin (Total)",
    //     "Biotin CHANGE",
    //     "Biotinidase",
    //     "Birch Components",
    //     "Bismuth",
    //     "BK Polyoma Virus by PCR",
    //     "Bleeding and Platelet Gene Panel",
    //     "Bleeding Disorder of Unknown Cause",
    //     "Blood Culture#",
    //     "Blood Film Examination",
    //     "Blood Group †",
    //     "Blood PCR for Chromosome 13, 18, 21 and sex chromosomes",
    //     "BNP (NT-pro BNP)",
    //     "Bone Alkaline Phosphatase",
    //     "Bone Marrow (Aspirate)",
    //     "Bone Marrow (Trephine Biopsy)",
    //     "Bone Screen",
    //     "Bone Screen (Bloods only)",
    //     "Borrelia Antibodies (Lyme Disease) IgG, IgM",
    //     "Borrelia Antibodies (Lyme Disease) IgM",
    //     "Borrelia Confirmation (Immunoblot)",
    //     "Brazil Components",
    //     "Breast Cancer – BRCA1 + BRCA2 genes only",
    //     "Breast Cancer Ashkenazi Screen – common variants",
    //     "Breast Cancer NGS Panel",
    //     "Bromide",
    //     "Brucella Serology",
    //     "Brugada Syndrome/Long QT Syndrome NGS Panel",
    //     "BUN (Blood Urea Nitrogen)",
    //     "C-KIT D816V variant – Mastocytosis",
    //     "C Reactive Protein (Self-collect)",
    //     "C Peptide",
    //     "C Reactive Protein (Venous / Self-collect)",
    //     "C Reactive Protein (High Sensitivity) (Self-collect)",
    //     "C Reactive Protein (High Sensitivity) (Venous / Self-collect)",
    //     "C1 Esterase Inhibitor",
    //     "C1 Esterase: Function & Total",
    //     "C1q Binding Immune Complex",
    //     "C3 Complement",
    //     "C3/C4 Complement",
    //     "C4 Complement",
    //     "CA 15-3",
    //     "CA 125 (Self-collect)",
    //     "CA 125 (Venous / Self-collect)",
    //     "CA 19-9",
    //     "CA 50",
    //     "CA 72-4",
    //     "CADASIL – NOTCH3 gene sequencing",
    //     "Cadmium (Blood)",
    //     "Cadmium (Urine)",
    //     "Caeruloplasmin",
    //     "CAKUT (Congenital Anomalies of Kidney & Urinary Tract) NGS Panel",
    //     "Calcitonin",
    //     "Calcium (24 hour Urine)",
    //     "Calcium (Self-collect)",
    //     "Calcium (Venous / Self-collect)",
    //     "Calcium + Vitamin D (Self-collect)",
    //     "Calcium + Vitamin D (Venous / Self-collect)",
    //     "Calcium/Creatinine Ratio",
    //     "Calprotectin",
    //     "Calprotectin (Self-collect)",
    //     "Calprotectin/QFIT Profile (Combined)",
    //     "Calprotectin/QFIT Profile (Combined) (Self-collect)",
    //     "Campylobacter Jejuni Antibodies",
    //     "Cancer, Comprehensive NGS Panel",
    //     "Candida (Culture)",
    //     "Candida Antibodies",
    //     "Cannabinoids (Urine) Screen",
    //     "Carbamazepine (Tegretol)",
    //     "Carbapenemase producing organism screen",
    //     "Carbohydrate Deficient Glycoprotein",
    //     "Carbohydrate Deficient Transferrin (CDT) (Self-collect)",
    //     "Carbohydrate Deficient Transferrin (CDT) (Venous / Self-collect)",
    //     "Carboxyhaemoglobin",
    //     "Carcino Embryonic Antigen",
    //     "Cardiolipin Antibodies (IgG+IgM)",
    //     "Cardiomyopathy, Dilated NGS Panel",
    //     "Cardiomyopathy, Hypertrophic NGS Panel",
    //     "Cardiovascular Risk Profile 1",
    //     "Cardiovascular Risk Profile 2",
    //     "Cardiovascular, Comprehensive NGS Panel",
    //     "Carotenes",
    //     "Carrier Screen (Ashkenazi Jewish)",
    //     "Carrier Screen (Ashkenazi Jewish) – Partnered Report",
    //     "Carrier Screen (Pan-Ethnic)",
    //     "Carrier Screen (Pan-Ethnic) – Partnered Report",
    //     "Cashew Components",
    //     "Cat Components",
    //     "Cat Scratch Fever (Bartonella IgG)",
    //     "Catecholamines (Plasma)",
    //     "Catecholamines (Urine)",
    //     "CCP Antibodies (RF)",
    //     "CD3/CD4/CD8",
    //     "CD16",
    //     "CD19 B Cells",
    //     "CD20",
    //     "D-Dimers (Fibrinogen Degradation Products)",
    //     "Dengue Fever PCR",
    //     "Dengue Virus Serology",
    //     "Deoxypyridinoline (DPD) – Serum",
    //     "Deoxypyridinoline (DPD) – Urine",
    //     "DHEA",
    //     "DHEA – Urine (Dehydroepiandrosterone)",
    //     "DHEA Sulphate (Venous / Self-collect)",
    //     "Diabetes – Obesity NGS Panel",
    //     "Diabetic Profile 1",
    //     "Diabetic Profile 2",
    //     "Diamine Oxidase Activity",
    //     "Diazepam (Valium)",
    //     "DiGeorge Syndrome (22q11 & 10p14 deletion) – BOBs (5 days) + karyotype (15 days)",
    //     "DiGeorge Syndrome (22q11 & 10p14) – BOBs only",
    //     "Digoxin",
    //     "Dihydropyrimidine Dehydrogenase deficiency screening (Fluoropyrimidine Toxicity)",
    //     "Dihydrotestosterone",
    //     "Dilated Cardiomyopathy NGS Panel",
    //     "Diphtheria Antibodies",
    //     "DL1 Biochemistry Profile",
    //     "DL1L Biochemistry Profile plus HDL Cholesterol, LDL Cholesterol and Non-HDL Cholesterol",
    //     "DL2 Biochemistry (24 Parameters) & Haematology Profile",
    //     "DL2L Biochemistry (24 Parameters) & Haematology Profile plus HDL Cholesterol, LDL Cholesterol and Non-HDL Cholesterol",
    //     "DL3 Haematology Profile",
    //     "DL4 Biochemistry (16 Parameters) & Haematology Profile",
    //     "DL4L Biochemistry (16 Parameters) & Haematology Profile plus HDL Cholesterol, LDL Cholesterol and Non-HDL Cholesterol",
    //     "DL5 Biochemistry & Haematology Postal Profile",
    //     "DL5L Biochemistry & Haematology Postal Profile plus HDL Cholesterol, LDL Cholesterol and Non-HDL Cholesterol",
    //     "DL6 General Well Person Profile",
    //     "DL6L General Well Person Profile plus HDL Cholesterol, LDL Cholesterol and Non-HDL Cholesterol",
    //     "DL7 Well Man Profile",
    //     "DL7L Well Man Profile plus HDL Cholesterol, LDL Cholesterol and Non-HDL Cholesterol",
    //     "DL8 Well Person Profile",
    //     "DL8L Well Person Profile plus HDL Cholesterol, LDL Cholesterol and Non-HDL Cholesterol",
    //     "DL9F Senior Female Profile 60+",
    //     "DL9M Senior Male Profile 60+",
    //     "DL10 Cardiovascular Risk Profile 1",
    //     "DL11 Cardiovascular Risk Profile 2",
    //     "DL12 7 STI Profile by PCR (7 PCR Tests from 1 Sample)",
    //     "DL12 7 STI Profile by PCR (7 PCR tests from 1 Sample) (Self-collect)",
    //     "DNA (Double Stranded) Antibodies IgG",
    //     "DNA (Single Stranded) Antibodies",
    //     "DNA Extraction & Storage – 3 years (longer upon request)",
    //     "DNA Identity Profile – 15 STR markers",
    //     "Dog Components",
    //     "Down Syndrome Risk Bloods only (Risk to be calculated by clinician)",
    //     "Down Syndrome Risk Profile (2nd trimester) Quad",
    //     "Down Syndrome Risk Profile with risk calculation first trimester",
    //     "Doxepin Level (Sinequan)",
    //     "Drugs of Abuse from Blood without Chain of Custody",
    //     "Drugs of Abuse Profile – Random Urine Sample/No Chain of Custody",
    //     "Drugs of Abuse Profile – Random Urine Sample/No Chain of Custody Plus Alcohol",
    //     "Drugs of Abuse Profile – With Chain of Custody*",
    //     "Drugs of Abuse Profile – Without Chain of Custody",
    //     "Duchenne Muscular Dystrophy – deletions/duplications only",
    //     "Duchenne Muscular Dystrophy – full sequencing DMD1 gene",
    //     "DVT/Pre-travel Screen",
    //     "Dysfibrinogenemia, congenital",
    //     "Dysplasminogenemia",
    //     "Dysprothrombinemia",
    //     "Echinococcus (Hydatid) Antibodies",
    //     "Egg Components",
    //     "Ehlers-Danlos Syndrome (associated with bleeding)",
    //     "Ehrlichiosis Antibodies",
    //     "Elastase (RF / Self-collect)",
    //     "Elastase (Self-collect)",
    //     "Electrolytes",
    //     "Electrolytes (Urine)",
    //     "ELF/Enhanced Liver Fibrosis",
    //     "Endometrial Cancer NGS Panel",
    //     "Endomysial Antibodies (IgA) (Venous / Self-collect)",
    //     "Endomysial Antibodies (IgA) (Self-collect)",
    //     "Enteric Organism Rapid Detection (RF / Self-collect)",
    //     "Eosin-5 Maleimide Dye binding test for Hereditary spherocytosis (EMA)*",
    //     "Eosinophil Cationic Protein",
    //     "Epanutin (Phenytoin)",
    //     "Epidermolysis Bullosa NGS Panel",
    //     "Epilepsy, Adolescent/Adult Onset Panel",
    //     "Epilepsy, Comprehensive NGS Panel",
    //     "Epstein-Barr Virus Antibodies IgG/IgM",
    //     "Epstein-Barr Virus PCR",
    //     "Erectile Dysfunction Profile",
    //     "Erythropoietin",
    //     "ESR",
    //     "Essential Fatty Acid Profile (Red Cell)",
    //     "Ethosuximide",
    //     "Extractable Nuclear Antibodies (nRNP, Sm, Ro, La, Jo1, Scl70) CENP-B",
    //     "Fabry Disease, X-linked – GLA gene sequencing",
    //     "Facioscapulohumeral Muscular Dystropy (FSHD) – D4Z4 repeat deletion",
    //     "Factor II Assay",
    //     "Factor II Deficiency (full gene analysis)",
    //     "Factor II Prothrombin – G20210A Variant",
    //     "Factor V and Factor VIII, combined deficiency of",
    //     "Factor V Assay",
    //     "Factor V Leiden – G1691A Variant",
    //     "Factor VIII Assay",
    //     "Factor VIII Inhibiting Antibody",
    //     "Factor IX Assay",
    //     "Factor IX Inhibiting Antibody",
    //     "Factor V Deficiency (full gene analysis)",
    //     "Factor VII Deficiency",
    //     "Factor X Assay",
    //     "Factor X Deficiency",
    //     "Factor XI Assay",
    //     "Factor XI Deficiency",
    //     "Factor XII Assay",
    //     "Factor XII Deficiency",
    //     "Factor XIII Assay",
    //     "Factor XIII Deficiency",
    //     "Faecal Fat (1 day collection)",
    //     "Faecal Fat (3 day)",
    //     "Faecal Lactoferrin",
    //     "Faecal Sugar Chromatography",
    //     "Familial Adenomatous Polyposis (FAP) NEW",
    //     "Familial Exudative Vitreoretinopathy (FEVR) NGS Panel – full gene sequencing",
    //     "Familial Hypercholesterolaemia NGS panel",
    //     "Familial Hypocalciuric Hypercalcaemia (FHH) Panel",
    //     "Familial Medullary Thyroid Carcinoma – hotspot sequencing RET gene",
    //     "Farmers Lung Precipitins",
    //     "Fasciola Hepatica Antibodies (Liver Fluke)",
    //     "FAST Chlamydia – PCR Swab",
    //     "FAST Chlamydia – Urine",
    //     "FAST CT/GC – PCR Swab",
    //     "FAST CT/GC – Rectal PCR Swab",
    //     "FAST CT/GC – Throat PCR Swab",
    //     "FAST CT/GC – Urine",
    //     "FAST Gonorrhoea – PCR Swab",
    //     "FAST Gonorrhoea – Urine",
    //     "FAST Screen SHORT with Swab",
    //     "FAST Screen with Swab",
    //     "FAST Screen with Urine",
    //     "Fasting Insulin Resistance Index (FIRI)",
    //     "Fatty Acid Oxidation Deficiency NGS Panel",
    //     "Female Hormone Profile (LH, FSH, PROL, TOES) (Self-collect)",
    //     "Female Hormone Profile (Venous / Self-collect)",
    //     "Ferritin (Self-collect)",
    //     "Ferritin (Venous / Self-collect)",
    //     "Ferritin (Venous / Self-collect)",
    //     "Fibrinogen",
    //     "Fibrotest (Liver Fibrosis)",
    //     "Filaria (Lymphatic and Non-Lymphatic) Antibodies",
    //     "First Trimester Antenatal Screen",
    //     "Fish Components",
    //     "FK506 (Tacrolimus/Prograf)",
    //     "Flecainide (Tambocor)",
    //     "Fletcher Factor (Prekallikrein) Deficiency",
    //     "FLT3-ITD and FLT3-TKD screening assay",
    //     "Fluid Culture",
    //     "Fluid Cytology",
    //     "Fluid for Crystals + Culture",
    //     "Fluoride (Urine)",
    //     "Fluoxetine (Prozac)",
    //     "Folate (Red Cell)",
    //     "Folate (Serum)",
    //     "Fragile X Syndrome screen – FMR1 repeat analysis PCR",
    //     "Free Fatty Acids",
    //     "Free T3 (Self-collect)",
    //     "Free T3 (Venous / Self-collect)",
    //     "Free T4 (Self-collect)",
    //     "Free T4 (Venous / Self-collect)",
    //     "Friedreich Ataxia – frataxin gene repeat analysis",
    //     "Fructosamine",
    //     "FSH (Self-collect)",
    //     "FSH (Venous / Self-collect)",
    //     "Full Blood Count",
    //     "Fungal ID + Sens",
    //     "Fungal investigations (non-superficial extended culture)",
    //     "Fungal investigations (superficial/dermatophyte PCR test)",
    //     "FXIII A Subunit",
    //     "G6PD",
    //     "Gabapentin",
    //     "Galactomanan (Aspergillus Antigen)",
    //     "Galactose-1-Phosphate Uridyltransferase",
    //     "Gall Stone Analysis",
    //     "Gamma GT",
    //     "Ganglionic Acetylcholine Receptor Antibodies",
    //     "Ganglioside GM1, GD1B, GQ1B Abs",
    //     "Gardnerella vaginalis by PCR",
    //     "Gastric Parietal Autoantibodies",
    //     "Gastrin",
    //     "Gastrointestinal Pathogen PCR (Self-collect)",
    //     "Gaucher Disease",
    //     "Gaucher Disease full gene sequencing",
    //     "Genetic Reproductive Profile (Male)",
    //     "Gentamicin Assay",
    //     "Ghosal Hematodiaphyseal Syndrome",
    //     "Giant Platelet Disorder",
    //     "Giardia Serology",
    //     "Gilbert Syndrome – common UGT1A1 repeat variation",
    //     "Glanzmann Thrombasthenia",
    //     "Gliadin Antibodies (IgG) (deamidated) (Self-collect)",
    //     "Gliadin Antibodies (IgG) (deamidated) (Venous / Self-collect)",
    //     "Globulin",
    //     "Glomerular Basement Membrane Abs",
    //     "Glucagon",
    //     "Glucose",
    //     "Glucose Challenge Test/Mini-GTT",
    //     "Glucose Tolerance Test (Extended Plus)",
    //     "Glucose Tolerance Test (Extended)",
    //     "Glucose Tolerance Test (Short)",
    //     "Glucose Tolerance Test/OGTT",
    //     "Glucose Tolerance with Growth Hormone",
    //     "Glucose Tolerance with Insulin",
    //     "Glutamic Acid Decarboxylase Antibodies (GAD 65)",
    //     "Glucose-6-Phosphate Dehydrogenase (G6PD) Deficiency – full G6PD gene sequencing",
    //     "Gluten Sensitivity Evaluation",
    //     "Gluten Sensitivity Profile CHANGE",
    //     "Gluten/Coeliac Genetic Profile 2 CHANGE",
    //     "Glycan Determinants",
    //     "Glycogen storage disease type 2 (Pompe) variant analysis",
    //     "Gonorrhoea – Culture",
    //     "Gonorrhoea – PCR swab",
    //     "Gonorrhoea – Thin Prep",
    //     "Gonorrhoea – Urine",
    //     "Granulocyte Immunology",
    //     "Gray Platelet Syndrome",
    //     "Group B Strep – Vaginal and Rectal (Self-collect)",
    //     "Group B Strep – Vaginal and Rectal (STM / Self-collect)",
    //     "Growth Hormone (Fasting)",
    //     "Gut Hormone Profile",
    //     "H. pylori Antibodies (IgG)",
    //     "H. pylori Antigen – Breath",
    //     "H. pylori Antigen – Stool (RF / Self-collect)",
    //     "H. pylori Antigen – Stool (Self-collect)",
    //     "H. pylori Culture",
    //     "Haematology Profile",
    //     "Haemochromatosis – HFE common variants C282Y + H63D",
    //     "Haemoglobin",
    //     "Haemoglobin Electrophoresis",
    //     "Haemophilia A (Factor VIII Deficiency)",
    //     "Haemophilia A (Factor VIII deficiency) – CVS",
    //     "Haemophilia B (Factor IX Deficiency)",
    //     "Haemophilia B (Factor IX deficiency) – CVS",
    //     "Haemophilus B Influenzae Antibodies",
    //     "Haemophilus ducreyi by PCR",
    //     "Haemosiderin (Urine)",
    //     "Hantavirus Serology",
    //     "Haptoglobin",
    //     "Hazelnut Components",
    //     "HbA1c (Self-collect)",
    //     "HbA1c (Venous / Self-collect)",
    //     "HCG (Oncology)",
    //     "HCG (Quantitative)",
    //     "HDL Cholesterol",
    //     "HE4 + ROMA (Earlier Detection of Ovarian Tumour)",
    //     "Hearing Loss NGS Panel",
    //     "Hemophagocytic Lymphohistiocytosis, Familial",
    //     "Hepatitis (Acute) Screen",
    //     "Hepatitis A (IgM)",
    //     "Hepatitis A Immunity (IgG/IgM)",
    //     "Hepatitis A Profile",
    //     "Hepatitis A RNA by PCR",
    //     "Hepatitis A, B & C Profile",
    //     "Hepatitis B (PCR) Genotype",
    //     "Hepatitis B ‘e’ Antigen and Antibody",
    //     "Hepatitis B Core Antibody – IgM",
    //     "Hepatitis B Core Antibody – Total",
    //     "Hepatitis B DNA (Viral load)",
    //     "Hepatitis B Immunity (IgG) (Self-collect)",
    //     "Hepatitis B Profile",
    //     "Hepatitis B Resistant Mutation",
    //     "Hepatitis B Surface Antigen (Self-collect)",
    //     "Hepatitis B Surface Antigen (Venous / Self-collect)",
    //     "Hepatitis C Abs Confirmation (RIBA)",
    //     "Hepatitis C Antibodies (Self-collect)",
    //     "Hepatitis C Antibodies (Venous / Self-collect)",
    //     "Hepatitis C Antigen (Early detection) (Venous / Self-collect)",
    //     "Hepatitis C Antigen (Early detection) (Venous / Self-collect)",
    //     "Hepatitis C Genotype",
    //     "Hepatitis C Quantification (Viral Load)",
    //     "Hepatitis Delta Antibody",
    //     "Hepatitis Delta RNA",
    //     "Hepatitis E (PCR)",
    //     "Hepatitis E IgG/IgM",
    //     "Hepatitis G (PCR)",
    //     "Hereditary Colorectal Cancer NGS Panel",
    //     "Hereditary Comprehensive Cancer NGS Panel",
    //     "Hereditary Neuropathy with Liability to Pressure Palsy – PMP22 deletion analysis"
    // ];

    const { tests, testsLoading } = useTest()

    const [selectedTest, setTest] = useState('All')
    const [filteredTest, setFilteredTest] = useState([...tests])

    useEffect(() => {
        if (selectedTest === 'All') {
            setFilteredTest([...tests])
        } else {
            const filtered = tests.filter(test => test?.title?.charAt(0).toLowerCase() === selectedTest?.toLowerCase())
            setFilteredTest([...filtered])
        }
    }, [selectedTest, tests])

    if (testsLoading) {
        return <TestListLoading />
    }
    return <main className="container mx-auto py-10">
        <TestsList allTests={filteredTest} setTest={setTest} selectedTest={selectedTest} />
    </main>;
}
