"use client"
import { useState } from "react";
import TestsList from "./TestList";


export default function PageA() {

    const testsA = [
        "1,25 Vitamin D",
        "1p36 Deletion Syndrome – karyotype + CGH",
        "2-Butanone GC",
        "2-Furoic Acid",
        "5 HIAA",
        "5’ Nucleotidase",
        "6-Thioguanine Nucleotides",
        "7 STI Profile by PCR (7 tests from 1 Sample)",
        "7 STI Profile by PCR (7 tests from 1 Sample) (Self-collect)",
        "11 Deoxycorticosterone",
        "11 Deoxycortisol",
        "16S rRNA Bacterial Gene",
        "17 Hydroxyprogesterone",
        "18S rRNA Fungal Gene",
        "21 Hydroxylase Ab’s",
        "21-Hydroxylase Deficiency (Congenital Adrenal Hyperplasia)",
        "22q11 & 10p14 deletion (Di George Syndrome) – BOBs only",
        "22q11 & 10p14 deletion (Di George Syndrome) – BOBs (5 days) + karyotype (15 days)",
        "Acetone – Blood",
        "Acetone – Urine",
        "Acetylcholine Receptor Autoantibodies",
        "Achromatopsia NGS Panel",
        "Acid Phosphatase – Total",
        "ACTH (Adrenocorticotropic Hormone)",
        "Activated Protein C Resistance",
        "Acute Viral Hepatitis Screen",
        "ADAMTS-13 Antibody",
        "Adenomatous Polyposis NGS Panel",
        "Adiponectin",
        "Adrenal Cortex Antibodies",
        "Afibrinogenemia, congenital",
        "Aicardi-Goutières Syndrome NGS Panel",
        "Alagille Syndrome NGS Panel",
        "Albumin",
        "Alcohol (Medical)",
        "Alcohol (Urine)",
        "Alcohol Profile",
        "Aldolase",
        "Aldosterone",
        "Aldosterone (Urine)",
        "ALEX® Allergy Test (Venous / Self-collect)",
        "Alkaline Phosphatase",
        "Alkaline Phosphatase Isoenzymes",
        "Allergic Rhinitis/Asthma Profile",
        "Allergy – Individual Allergens",
        "Allergy – 10 x Single Individual Allergens",
        "Allergy Profile 1 (Food & Inhalants)",
        "Allergy Profile 2 (UK Aero Allergen)",
        "Allergy Profile 3 (Food)",
        "Allergy Profile 4 (Nuts & Seeds)",
        "Allergy Profile 5 (Children’s Panel)",
        "Allergy Profile 7 (Finfish)",
        "Allergy Profile 6 (Shellfish)",
        "Allergy Profile 8 (Cereal – singles)",
        "Allergy Profile 9 (Antibiotics)",
        "Allergy Profile 10 (Insects)",
        "Allergy Profile 11 (Combined Shellfish/Finfish)",
        "Allergy Profile 12 (Milk & Milk Proteins)",
        "Allergy Profile 13 (Stone fruit/Rosaceae family)",
        "Gaucher Disease full gene sequencing",
        "H. pylori Antigen – Stool (Self-collect)",
        "Hazelnut Components",
        "Hepatitis A, B & C Profile"
    ];
    const testsB = [
        "B cell clonality assay (IgH and IgK)",
        "Babesia PCR",
        "Bancroftia/Oncerciasis/Filarial Antibodies",
        "Bardet-Biedl Syndrome NGS Panel",
        "Batten Disease (Neuronal Ceroid Lipofuscinosis) NGS Panel",
        "BCR-ABL Diagnostic Assay",
        "BCR/ABL Quantitative – fusion gene sizes p190 + p210",
        "Becker/Duchenne Muscular Dystrophy – deletions/duplications",
        "Beckwith-Wiedemann Syndrome – methylation studies on 11p15 imprinting domains KvDMR + H19",
        "Behcet’s Disease – HLA Tissue Typing B*51",
        "Bence-Jones Protein",
        "Benzene",
        "Bernard-Soulier Syndrome",
        "Beta 2 Microglobulin (Serum)",
        "Beta 2 Microglobulin (Urine)",
        "Beta Carotene",
        "Beta D Glucan",
        "Beta Thalassaemia – beta-globin gene sequencing",
        "Beta-Glucuronidase (Sly Disease)",
        "Bicarbonate",
        "Bile Acids – Serum",
        "Bilharzia (Schistosome) Antibody Screen",
        "Bilharzia (Urine)",
        "Bilirubin (Direct)",
        "Bilirubin (Total)",
        "Biotin CHANGE",
        "Biotinidase",
        "Birch Components",
        "Bismuth",
        "BK Polyoma Virus by PCR",
        "Bleeding and Platelet Gene Panel",
        "Bleeding Disorder of Unknown Cause",
        "Blood Culture#",
        "Blood Film Examination",
        "Blood Group †",
        "Blood PCR for Chromosome 13, 18, 21 and sex chromosomes",
        "BNP (NT-pro BNP)",
        "Bone Alkaline Phosphatase",
        "Bone Marrow (Aspirate)",
        "Bone Marrow (Trephine Biopsy)",
        "Bone Screen",
        "Bone Screen (Bloods only)",
        "Borrelia Antibodies (Lyme Disease) IgG, IgM",
        "Borrelia Antibodies (Lyme Disease) IgM",
        "Borrelia Confirmation (Immunoblot)",
        "Brazil Components",
        "Breast Cancer – BRCA1 + BRCA2 genes only",
        "Breast Cancer Ashkenazi Screen – common variants",
        "Breast Cancer NGS Panel",
        "Bromide",
        "Brucella Serology",
        "Brugada Syndrome/Long QT Syndrome NGS Panel",
        "BUN (Blood Urea Nitrogen)"
    ];

    const test = [testsA, testsB]
    const [selectedTest, setTest] = useState([1])
    return <main className="container mx-auto py-10 pt-48">
        <TestsList allTests={test[selectedTest]} setTest={setTest} selectedTest={selectedTest} />
    </main>;
}
